#!/bin/sh
# Source: https://github.com/geerlingguy/docker-ubuntu2204-ansible/blob/33e2cd83f55b88b0ad85dce17171ef13de3f2912/initctl_faker

ALIAS_CMD="$(echo "$0" | sed -e 's?/sbin/??')"

case "$ALIAS_CMD" in
    start|stop|restart|reload|status)
        exec service "$1" "$ALIAS_CMD"
        ;;
esac

case "$1" in
    list )
        exec service --status-all
        ;;
    reload-configuration )
        exec service "$2" restart
        ;;
    start|stop|restart|reload|status)
        exec service "$2" "$1"
        ;;
    \?)
        exit 0
        ;;
esac
